remote_theme: pages-themes/cayman@v0.2.0
plugins:
title: [YbicG's Portfolio]
description: [Hello! I am a 16 year old scripter from the US. I am very dilligent and I will complete my work on time! Reach out to me on Discord | YbicG#1258]
show_downloads: [false]
