remote_theme: pages-themes/cayman@v0.2.0
plugins:
title: YbicG's Portfolio
description: Hello! I am a professional scripter from the US. I am very dilligent and I complete my work on time! Reach out to me on Discord | 7bic
show_downloads: false
